'use client';
import {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {createClient} from '../../lib/supabase/client';
import {configured} from '../../lib/supabase/config';
import {safeReturn} from '../../lib/redirect';
import {Clapperboard,ChevronLeft} from 'lucide-react';
export default function Login(){const params=useSearchParams();const next=safeReturn(params.get('return_to'));const [email,setEmail]=useState(''),[token,setToken]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(params.get('error')?'로그인 링크가 만료되었거나 유효하지 않습니다. 다시 시도해 주세요.':'');
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const supabase=createClient();if(!sent){const {error}=await supabase.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:true,emailRedirectTo:window.location.origin+'/auth/callback?next='+encodeURIComponent(next)}});if(error)throw error;setSent(true)}else{const {error}=await supabase.auth.verifyOtp({email:email.trim(),token:token.trim(),type:'email'});if(error)throw error;window.location.assign(next)}}catch(e){console.error(e);setError(sent?'인증 코드를 확인해 주세요. 만료됐다면 새 코드를 요청해 주세요.':'인증 메일을 보내지 못했습니다. 이메일 주소 또는 작업실의 메일 발송 설정을 확인해 주세요.')}finally{setBusy(false)}}
return <div className="loginpage"><a href="/" className="backhome"><ChevronLeft size={18}/>작업실로 돌아가기</a><section className="loginpanel"><Clapperboard size={37}/><span className="eyebrow">SCENE ROOM</span><h1>우리의 다음 장면을 쓰러</h1><p>{sent?'메일로 받은 인증 코드를 입력해 주세요.':'이메일로 로그인하고, 나만의 집필실에서 시작하세요.'}</p>{!configured()?<div role="alert" className="error">작업실 연결 설정을 준비 중입니다. 운영자가 Supabase 환경 변수를 설정해야 로그인할 수 있습니다.</div>:<form onSubmit={submit}><label>이메일<input type="email" required autoComplete="email" value={email} disabled={sent} onChange={e=>setEmail(e.target.value)} placeholder="writer@example.com"/></label>{sent&&<label>인증 코드<input required inputMode="numeric" autoComplete="one-time-code" minLength={6} maxLength={10} value={token} onChange={e=>setToken(e.target.value.replace(/\D/g,''))} placeholder="메일에 표시된 숫자"/></label>}{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="primary">{busy?'확인 중…':sent?'로그인':'인증 코드 받기'}</button>{sent&&<button className="soft" type="button" disabled={busy} onClick={()=>{setSent(false);setToken('')}}>이메일 변경 / 새 코드 요청</button>}</form>}<p className="muted">처음 방문하면 계정이 만들어집니다. 로그인 후 스터디용 프로필을 정할 수 있어요.</p></section></div>}
